### ISSUE TITLE
Error in creating rails cartridge after installation

### ISSUE THREAD

**Issue by yrougy** [openshift/openshift-extras#278]
Hello,

I have a missing library (actually it was 2), after a fresh install of Openshift Origin with the installer, on a CentOS 6.

The error message was that it cannot find libhttp_parser.

I've managed to make it work by copying
/opt/rh/nodejs010/root/usr/lib64/libhttp_parser\* in /opt/rh/ruby193/root/usr/lib64
and copying
/opt/rh/ruby193/root/lib64/libuv.so.0.10  in /opt/rh/ruby193/root/usr/lib64

It's dirty but it made it work.

Y.

**Comment by akostadinov** [comment]
you could enable in Gemfile the `gem 'therubyracer', platforms: :ruby` line. In this way execjs would use therhinoracer gem and avoid need for linuv (needed for Node.js runtime). Or use some other runtime like Rhino.
