### ISSUE TITLE
oo-install silent errors on CentOS

### ISSUE THREAD

**Issue by strobe** [openshift/openshift-extras#287]
I have been tried to install openshift on single VM (on OpenLogic 6.5 in Azure Cloud and locally on vagrant vm with CentOS 6.5 ) by sh <(curl -s https://install.openshift.com/) and http://openshift.github.io/documentation/oo_install_users_guide.html instructions. But at end I got this output:

```
* Target host is running non-Fedora, non-RHEL
* Located getenforce... can invoke 'getenforce' with sudo
* SELinux is running in enforcing mode
* Located yum... can invoke 'yum' with sudo
* Located puppet... can invoke 'puppet' with sudo
* Located dnssec-keygen... can invoke 'dnssec-keygen' with sudo
* Located htpasswd... can invoke 'htpasswd' with sudo
* Located scl... can invoke 'scl' with sudo
* The ruby193 software collection is installed.
* epel repository is present and enabled

Deploying workflow 'origin_deploy'.
Setting up htpasswd for default user account.

Preparing to install OpenShift Origin on the following hosts:
  * localhost: msgserver, dbserver, broker, node
Deploying host 'openshift.cloudapp.net'

Checking for DNS key on localhost...
...found at /var/named/Kopenshift.cloudapp.net*.key
bash: systemctl: command not found
Command 'systemctl' didn't work; trying older style...
Older style system command succeeded.

Running Puppet deployment

Running "sudo bash -l -c 'scl enable ruby193 "puppet module list"'"...
Command completed.

Running "sudo bash -l -c 'scl enable ruby193 "puppet module install openshift/openshift_origin"'"...
Command completed.

Running "sudo bash -l -c 'yum clean all'"...
Command completed.

Running "sudo bash -l -c 'scl enable ruby193 "puppet apply --verbose /tmp/oo_install_configure_openshift.cloudapp.net.pp"'"...
Command completed.

Running "sudo bash -l -c 'rm /tmp/oo_install_configure_openshift.cloudapp.net.pp'"...
[sudo] password for azureuser:
```

**Warning: There were errors during the deployment on host** 'openshift.cloudapp.net'.

```
OpenShift Origin deployment completed.
You should manually reboot openshift.cloudapp.net to complete the process.

All tasks completed.
```

All looks like broker don't started on this machine:
- /var/log doesn't have openshift folder
- rhc setup return 
  `Unable to connect to the server (Connection refused - connect(2) (https://localhost:443)). Check that you have correctly
  specified your OpenShift server 'https://localhost/broker/rest/api'.
  ` - from localhost and from remote host
- curl https://localhost/broker/rest/api
  curl: (7) couldn't connect to host
- curl http://localhost/broker/rest/api

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /broker/rest/api was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at localhost Port 80</address>
</body></html>
```

How can I detect issue reason?

**Comment by giuseppegaleota** [comment]
Hi all
I am trying to automate deploy OpenShift Origin into OpenStack by Heat using this template:
https://github.com/openstack/heat-templates/blob/master/openshift-origin/centos65/OpenShift.yaml 
I have used a centos-6.5-x86_64 image with preinstalled cfntools.

I can see the following into the /var/log/configure_origin.log:

...
...
Info: /Stage[main]/Openshift_origin::Plugins::Auth::Htpasswd/File[Auth plugin config]: Scheduling refresh of Service[openshift-broker]
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install openshift-origin-cartridge-python' returned 1: Error: Package: python33-mod_wsgi-3.4-9.el6.x86_64 (origin-deps)
           Requires: httpd24-httpd-mmn = 20120211x8664
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: /Stage[main]/Openshift_origin::Cartridges/Openshift_origin::Cartridges::Openshiftcartridge[python]/Package[openshift-origin-cartridge-python]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install openshift-origin-cartridge-python' returned 1: Error: Package: python33-mod_wsgi-3.4-9.el6.x86_64 (origin-deps)
           Requires: httpd24-httpd-mmn = 20120211x8664
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


*1) What does this error mean?*


Moreover, despite that error the installation process continues:
Notice: /Stage[main]/Openshift_origin::Plugins::Dns::Nsupdate/File[plugin openshift-origin-dns-nsupdate.conf]/ensure: defined content as '{md5}2b8e9cfc7f82dc303c3a6fbd9fa14fcb'
Notice: /Stage[main]/Openshift_origin::Plugins::Frontend::Apache_mod_rewrite/Package[rubygem-openshift-origin-frontend-apache-mod-rewrite]/ensure: created
Notice: /Stage[main]/Openshift_origin::Cartridges/Openshift_origin::Cartridges::Openshiftcartridge[cron]/Package[openshift-origin-cartridge-cron]/ensure: created
Info: /Stage[main]/Openshift_origin::Cartridges/Openshift_origin::Cartridges::Openshiftcartridge[cron]/Package[openshift-origin-cartridge-cron]: Scheduling refresh of Service[ruby193-mcollective]

but now it is blocked on the last row.
*2) Why does this status happen?*

Thank you very much,
Giuseppe
