### ISSUE TITLE
Origin M4 script not found

### ISSUE THREAD

**Issue by joubertredrat** [openshift/openshift-extras#540]
Hi guys,

M4 install script on https://install.openshift.com/origin-m4 was removed and I can't install from source, how to I get this script?

**Comment by detiber** [comment]
@brenton I would hazard a guess that someone updated install.openshfit.com using a branch other than master for openshift-extras....

**Comment by brenton** [comment]
@joubertredrat, mind trying again?  Something bizarre seems to have happened during the last push to install.openshift.com and some parts were missing.

**Comment by joubertredrat** [comment]
Hi @brenton I will try here now

**Comment by joubertredrat** [comment]
Hi @brenton thanks guys, worked fine here, thanks!
```
[root@master ~]# sh <(curl -s https://install.openshift.com/origin-m4)
Checking for necessary tools...
...looks good.
Downloading oo-install package...
Extracting oo-install to temporary directory...
Starting oo-install...
OpenShift Installer (Build 20151120-1810)
----------------------------------------------------------------------

Welcome to OpenShift.

... ... ...

Be sure to record these somewhere for future use.

Local temporary files removed.

Deployment successful. Exiting installer.

All tasks completed.
oo-install exited; removing temporary assets.
```
